name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@1

      - name: Publish package
        uses: gradle/gradle-build-action@2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
